added debug to deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,6 +39,15 @@ jobs:
         run: |
           cd web
           npm run build
+      - name: Debug: show files
+        run: |
+          echo "== SERVER =="
+          ls -lah server || echo "server folder missing"
+          echo "== CLIENT =="
+          ls -lah client || echo "client folder missing"
+          echo "== WEB DIST =="
+          ls -lah web/dist || echo "web/dist folder missing"
+
 
       - name: Deploy to server (SCP)
         uses: appleboy/scp-action@v0.1.7
