changed dist to build

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,8 +39,8 @@ jobs:
         run: |
           echo "Checking contents of web/"
           ls -lah web
-          echo "Checking contents of web/dist/"
-          ls -lah web/dist || echo "dist does not exist"
+          echo "Checking contents of web/build/"
+          ls -lah web/build || echo "dist does not exist"
 
 
       - name: Debug - show files
@@ -50,7 +50,7 @@ jobs:
           echo "== CLIENT =="
           ls -lah client || echo "client folder missing"
           echo "== WEB DIST =="
-          ls -lah web/dist || echo "web/dist folder missing"
+          ls -lah web/build || echo "web/build folder missing"
 
       - name: Deploy to server (SCP)
         uses: appleboy/scp-action@v0.1.7
@@ -61,7 +61,7 @@ jobs:
           source: |
             server/*
             client/*
-            web/dist/*
+            web/build/*
           target: /home/gta/
           port: 22
           timeout: 30s
